export const blake = [
    {
        title: "London",
        author: "William Blake",
        lines: [
            "I wandered through each chartered street,",
            "  Near where the chartered Thames does flow,",
            "A mark in every face I meet,",
            "  Marks of weakness, marks of woe.",
            "",
            "In every cry of every man,",
            "  In every infant's cry of fear,",
            "In every voice, in every ban,",
            "  The mind-forged manacles I hear:",
            "",
            "How the chimney-sweeper's cry",
            "  Every blackening church appalls,",
            "And the hapless soldier's sigh",
            "  Runs in blood down palace-walls.",
            "",
            "But most, through midnight streets I hear",
            "  How the youthful harlot's curse",
            "Blasts the new-born infant's tear,",
            "  And blights with plagues the marriage-hearse."
        ],
        linecount: 16
    },
    {
        title: "A POISON TREE",
        author: "William Blake",
        lines: [
            "I was angry with my friend:",
            "I told my wrath, my wrath did end.",
            "I was angry with my foe:",
            "I told it not, my wrath did grow.",
            "",
            "And I watered it in fears",
            "Night and morning with my tears,",
            "And I sunned it with smiles",
            "And with soft deceitful wiles.",
            "",
            "And it grew both day and night,",
            "Till it bore an apple bright,",
            "And my foe beheld it shine,",
            "and he knew that it was mine,--",
            "",
            "And into my garden stole",
            "When the night had veiled the pole;",
            "In the morning, glad, I see",
            "My foe outstretched beneath the tree."
        ],
        linecount: 16
    },
    {
        title: "Thel's Motto",
        author: "William Blake",
        lines: [
            "Does the Eagle know what is in the pit?",
            "Or wilt thou go ask the Mole:",
            "Can Wisdom be put in a silver rod?",
            "Or Love in a golden bowl?"
        ],
        linecount: 4
    },
    {
        title: "Songs of Innocence: Introduction",
        author: "William Blake",
        lines: [
            "Piping down the valleys wild,",
            "  Piping songs of pleasant glee,",
            "On a cloud I saw a child,",
            "  And he laughing said to me:",
            "",
            '"Pipe a song about a Lamb!"',
            "  So I piped with merry cheer.",
            '"Piper, pipe that song again;"',
            "  So I piped: he wept to hear.",
            "",
            '"Drop thy pipe, thy happy pipe;',
            '  Sing thy songs of happy cheer!"',
            "So I sang the same again,",
            "  While he wept with joy to hear.",
            "",
            '"Piper, sit thee down and write',
            '  In a book, that all may read."',
            "So he vanish'd from my sight;",
            "  And I pluck'd a hollow reed,",
            "",
            "And I made a rural pen,",
            "  And I stain'd the water clear,",
            "And I wrote my happy songs",
            "  Every child may joy to hear."
        ],
        linecount: 20
    },
    {
        title: "The Lamb",
        author: "William Blake",
        lines: [
            "  Little Lamb, who made thee",
            "  Dost thou know who made thee,",
            "Gave thee life, and bid thee feed",
            "By the stream and o'er the mead;",
            "Gave thee clothing of delight,",
            "Softest clothing, woolly, bright;",
            "Gave thee such a tender voice,",
            "Making all the vales rejoice?",
            "  Little Lamb, who made thee?",
            "  Dost thou know who made thee?",
            "",
            "  Little Lamb, I'll tell thee;",
            "  Little Lamb, I'll tell thee:",
            "He is called by thy name,",
            "For He calls Himself a Lamb",
            "He is meek, and He is mild,",
            "He became a little child.",
            "I a child, and thou a lamb,",
            "We are called by His name.",
            "  Little Lamb, God bless thee!",
            "  Little Lamb, God bless thee!"
        ],
        linecount: 20
    },
    {
        title: "The Blossom",
        author: "William Blake",
        lines: [
            "Merry, merry sparrow!",
            "Under leaves so green",
            "A happy blossom",
            "Sees you, swift as arrow,",
            "Seek your cradle narrow,",
            "Near my bosom.",
            "Pretty, pretty robin!",
            "Under leaves so green",
            "A happy blossom",
            "Hears you sobbing, sobbing,",
            "Pretty, pretty robin,",
            "Near my bosom."
        ],
        linecount: 12
    },
    {
        title: "The Little Boy Lost",
        author: "William Blake",
        lines: [
            '"Father, father, where are you going?',
            "  Oh do not walk so fast!",
            "Speak, father, speak to your little boy,",
            '  Or else I shall be lost."',
            "",
            "The night was dark, no father was there,",
            "  The child was wet with dew;",
            "The mire was deep, and the child did weep,",
            "  And away the vapour flew."
        ],
        linecount: 8
    },
    {
        title: "The Little Boy Found",
        author: "William Blake",
        lines: [
            "The little boy lost in the lonely fen,",
            "  Led by the wandering light,",
            "Began to cry, but God, ever nigh,",
            "  Appeared like his father, in white.",
            "",
            "He kissed the child, and by the hand led,",
            "  And to his mother brought,",
            "Who in sorrow pale, through the lonely dale,",
            "  The little boy weeping sought."
        ],
        linecount: 8
    },
    {
        title: "Laughing Song",
        author: "William Blake",
        lines: [
            "When the green woods laugh with the voice of joy,",
            "And the dimpling stream runs laughing by;",
            "When the air does laugh with our merry wit,",
            "And the green hill laughs with the noise of it;",
            "",
            "when the meadows laugh with lively green,",
            "And the grasshopper laughs in the merry scene,",
            "When Mary and Susan and Emily",
            'With their sweet round mouths sing "Ha, ha he!"',
            "",
            "When the painted birds laugh in the shade,",
            "Where our table with cherries and nuts is spread:",
            "Come live, and be merry, and join with me,",
            'To sing the sweet chorus of "Ha, ha, he!"'
        ],
        linecount: 12
    },
    {
        title: "Holy Thursday",
        author: "William Blake",
        lines: [
            "'Twas on a Holy Thursday, their innocent faces clean,",
            "Came children walking two and two, in read, and blue, and green:",
            "Grey-headed beadles walked before, with wands as white as snow,",
            "Till into the high dome of Paul's they like Thames waters flow.",
            "",
            "Oh what a multitude they seemed, these flowers of London town!",
            "Seated in companies they sit, with radiance all their own.",
            "The hum of multitudes was there, but multitudes of lambs,",
            "Thousands of little boys and girls raising their innocent hands.",
            "",
            "Now like a mighty wild they raise to heaven the voice of song,",
            "Or like harmonious thunderings the seats of heaven among:",
            "Beneath them sit the aged man, wise guardians of the poor.",
            "Then cherish pity, lest you drive an angel from your door."
        ],
        linecount: 12
    },
    {
        title: "Nurse's Song",
        author: "William Blake",
        lines: [
            "When the voices of children are heard on the green,",
            "  And laughing is heard on the hill,",
            "My heart is at rest within my breast,",
            "  And everything else is still.",
            '"Then come home, my children, the sun is gone down,',
            "  And the dews of night arise;",
            "Come, come, leave off play, and let us away,",
            '  Till the morning appears in the skies."',
            "",
            '"No, no, let us play, for it is yet day,',
            "  And we cannot go to sleep;",
            "Besides, in the sky the little birds fly,",
            '  And the hills are all covered with sheep."',
            '"Well, well, go and play till the light fades away,',
            '  And then go home to bed."',
            "The little ones leaped, and shouted, and laughed,",
            "  And all the hills echoed."
        ],
        linecount: 16
    },
    {
        title: "A DREAM",
        author: "William Blake",
        lines: [
            "Once a dream did weave a shade",
            "O'er my angel-guarded bed,",
            "That an emmet lost its way",
            "Where on grass methought I lay.",
            "",
            "Troubled, wildered, and forlorn,",
            "Dark, benighted, travel-worn,",
            "Over many a tangle spray,",
            "All heart-broke, I heard her say:",
            "",
            '"Oh my children! do they cry,',
            "Do they hear their father sigh?",
            "Now they look abroad to see,",
            'Now return and weep for me."',
            "",
            "Pitying, I dropped a tear:",
            "But I saw a glow-worm near,",
            'Who replied, "What wailing wight',
            "Calls the watchman of the night?",
            "",
            '"I am set to light the ground,',
            "While the beetle goes his round:",
            "Follow now the beetle's hum;",
            'Little wanderer, hie thee home!"'
        ],
        linecount: 20
    },
    {
        title: "Songs of Experience: Introduction",
        author: "William Blake",
        lines: [
            "Hear the voice of the Bard,",
            "Who present, past, and future, sees;",
            "Whose ears have heard",
            "The Holy Word",
            "That walked among the ancient tree;",
            "",
            "Calling the lapsed soul,",
            "And weeping in the evening dew;",
            "That might control",
            "The starry pole,",
            "And fallen, fallen light renew!",
            "",
            '"O Earth, O Earth, return!',
            "Arise from out the dewy grass!",
            "Night is worn,",
            "And the morn",
            "Rises from the slumbrous mass.",
            "",
            '"Turn away no more;',
            "Why wilt thou turn away?",
            "The starry floor,",
            "The watery shore,",
            'Are given thee till the break of day."'
        ],
        linecount: 20
    },
    {
        title: "The Clod and the Pebble",
        author: "William Blake",
        lines: [
            '"Love seeketh not itself to please,',
            "  Nor for itself hath any care,",
            "But for another gives it ease,",
            "  And builds a heaven in hell's despair.\"",
            "",
            "So sang a little clod of clay,",
            "  Trodden with the cattle's feet,",
            "But a pebble of the brook",
            "  Warbled out these metres meet:",
            "",
            '"Love seeketh only Self to please,',
            "  To bind another to its delight,",
            "Joys in another's loss of ease,",
            "  And builds a hell in heaven's despite.\""
        ],
        linecount: 12
    },
    {
        title: "Holy Thursday",
        author: "William Blake",
        lines: [
            "Is this a holy thing to see",
            "  In a rich and fruitful land,--",
            "Babes reduced to misery,",
            "  Fed with cold and usurous hand?",
            "",
            "Is that trembling cry a song?",
            "  Can it be a song of joy?",
            "And so many children poor?",
            "  It is a land of poverty!",
            "",
            "And their son does never shine,",
            "  And their fields are bleak and bare,",
            "And their ways are filled with thorns:",
            "  It is eternal winter there.",
            "",
            "For where'er the sun does shine,",
            "  And where'er the rain does fall,",
            "Babes should never hunger there,",
            "  Nor poverty the mind appall."
        ],
        linecount: 16
    },
    {
        title: "The Chimney Sweeper",
        author: "William Blake",
        lines: [
            "A little black thing in the snow,",
            'Crying "weep! weep!" in notes of woe!',
            '"Where are thy father and mother? Say!"--',
            '"They are both gone up to the church to pray.',
            "",
            '"Because I was happy upon the heath,',
            "And smiled among the winter's snow,",
            "They clothed me in the clothes of death,",
            "And taught me to sing the notes of woe.",
            "",
            '"And because I am happy and dance and sing,',
            "They think they have done me no injury,",
            "And are gone to praise God and his priest and king,",
            'Who make up a heaven of our misery."'
        ],
        linecount: 12
    },
    {
        title: "Nurse's Song",
        author: "William Blake",
        lines: [
            "When voices of children are heard on the green,",
            "And whisperings are in the dale,",
            "The days of my youth rise fresh in my mind,",
            "My face turns green and pale.",
            "",
            "Then come home, my children, the sun is gone down,",
            "And the dews of night arise;",
            "Your spring and your day are wasted in play,",
            "And your winter and night in disguise."
        ],
        linecount: 8
    },
    {
        title: "The Sick Rose",
        author: "William Blake",
        lines: [
            "O rose, thou art sick!",
            "  The invisible worm,",
            "That flies in the night,",
            "  In the howling storm,",
            "",
            "Has found out thy bed",
            "  Of crimson joy,",
            "And his dark secret love",
            "  Does thy life destroy."
        ],
        linecount: 8
    },
    {
        title: "The Angel",
        author: "William Blake",
        lines: [
            "I dreamt a dream!  What can it mean?",
            "And that I was a maiden Queen",
            "Guarded by an Angel mild:",
            "Witless woe was ne'er beguiled!",
            "",
            "And I wept both night and day,",
            "And he wiped my tears away;",
            "And I wept both day and night,",
            "And hid from him my heart's delight.",
            "",
            "So he took his wings, and fled;",
            "Then the morn blushed rosy red.",
            "I dried my tears, and armed my fears",
            "With ten-thousand shields and spears.",
            "",
            "Soon my Angel came again;",
            "I was armed, he came in vain;",
            "For the time of youth was fled,",
            "And grey hairs were on my head."
        ],
        linecount: 16
    },
    {
        title: "My Pretty Rose Tree",
        author: "William Blake",
        lines: [
            "A flower was offered to me,",
            "  Such a flower as May never bore;",
            'But I said "I\'ve a pretty rose tree,"',
            "  And I passed the sweet flower o'er.",
            "",
            "Then I went to my pretty rose tree,",
            "  To tend her by day and by night;",
            "But my rose turned away with jealousy,",
            "  And her thorns were my only delight."
        ],
        linecount: 8
    },
    {
        title: "The Lily",
        author: "William Blake",
        lines: [
            "The modest Rose puts forth a thorn,",
            "The humble sheep a threat'ning horn:",
            "While the Lily white shall in love delight,",
            "Nor a thorn nor a threat stain her beauty bright."
        ],
        linecount: 4
    },
    {
        title: "The Little Vagabond",
        author: "William Blake",
        lines: [
            "Dear mother, dear mother, the Church is cold;",
            "But the Alehouse is healthy, and pleasant, and warm.",
            "Besides, I can tell where I am used well;",
            "The poor parsons with wind like a blown bladder swell.",
            "",
            "But, if at the Church they would give us some ale,",
            "And a pleasant fire our souls to regale,",
            "We'd sing and we'd pray all the livelong day,",
            "Nor ever once wish from the Church to stray.",
            "",
            "Then the Parson might preach, and drink, and sing,",
            "And we'd be as happy as birds in the spring;",
            "And modest Dame Lurch, who is always at church,",
            "Would not have bandy children, nor fasting, nor birch.",
            "",
            "And God, like a father, rejoicing to see",
            "His children as pleasant and happy as he,",
            "Would have no more quarrel with the Devil or the barrel,",
            "But kiss him, and give him both drink and apparel."
        ],
        linecount: 16
    },
    {
        title: "Infant Sorrow",
        author: "William Blake",
        lines: [
            "My mother groaned, my father wept:",
            "Into the dangerous world I leapt,",
            "Helpless, naked, piping loud,",
            "Like a fiend hid in a cloud.",
            "",
            "Struggling in my father's hands,",
            "Striving against my swaddling-bands,",
            "Bound and weary, I thought best",
            "To sulk upon my mother's breast."
        ],
        linecount: 8
    },
    {
        title: "To Tirzah",
        author: "William Blake",
        lines: [
            "Whate'er is born of mortal birth",
            "Must be consumed with the earth,",
            "To rise from generation free:",
            "Then what have I to do with thee?",
            "The sexes sprang from shame and pride,",
            "Blown in the morn, in evening died;",
            "But mercy changed death into sleep;",
            "The sexes rose to work and weep.",
            "",
            "Thou, mother of my mortal part,",
            "With cruelty didst mould my heart,",
            "And with false self-deceiving tears",
            "Didst bind my nostrils, eyes, and ears,",
            "",
            "Didst close my tongue in senseless clay,",
            "And me to mortal life betray.",
            "The death of Jesus set me free:",
            "Then what have I to do with thee?"
        ],
        linecount: 16
    },
    {
        title: "The Voice of the Ancient Bard",
        author: "William Blake",
        lines: [
            "Youth of delight!  come hither",
            "And see the opening morn,",
            "Image of Truth new-born.",
            "Doubt is fled, and clouds of reason,",
            "Dark disputes and artful teazing.",
            "Folly is an endless maze;",
            "Tangled roots perplex her ways;",
            "How many have fallen there!",
            "They stumble all night over bones of the dead;",
            "And feel--they know not what but care;",
            "And wish to lead others, when they should be led."
        ],
        linecount: 11
    },
    {
        title: "The Shepherd",
        author: "William Blake",
        lines: [
            "How sweet is the Shepherd's sweet lot!",
            "From the morn to the evening he stays;",
            "He shall follow his sheep all the day,",
            "And his tongue shall be filled with praise.",
            "",
            "For he hears the lambs' innocent call,",
            "And he hears the ewes' tender reply;",
            "He is watching while they are in peace,",
            "For they know when their Shepherd is nigh."
        ],
        linecount: 8
    },
    {
        title: "Infant Joy",
        author: "William Blake",
        lines: [
            '"I have no name;',
            'I am but two days old."',
            "What shall I call thee?",
            '"I happy am,',
            'Joy is my name."',
            "Sweet joy befall thee!",
            "",
            "Pretty joy!",
            "Sweet joy, but two days old.",
            "Sweet Joy I call thee:",
            "Thou dost smile,",
            "I sing the while;",
            "Sweet joy befall thee!"
        ],
        linecount: 12
    },
    {
        title: "Ah Sunflower",
        author: "William Blake",
        lines: [
            "Ah Sunflower, weary of time,",
            "  Who countest the steps of the sun;",
            "Seeking after that sweet golden clime",
            "  Where the traveller's journey is done;",
            "",
            "Where the Youth pined away with desire,",
            "  And the pale virgin shrouded in snow,",
            "Arise from their graves, and aspire",
            "  Where my Sunflower wishes to go!"
        ],
        linecount: 8
    },
    {
        title: "A DIVINE IMAGE",
        author: "William Blake",
        lines: [
            "Cruelty has a human heart,",
            "  And Jealousy a human face;",
            "Terror the human form divine,",
            "  And Secresy the human dress.",
            "",
            "The human dress is forged iron,",
            "  The human form a fiery forge,",
            "The human face a furnace sealed,",
            "  The human heart its hungry gorge."
        ],
        linecount: 8
    }
];
