export const keats = [
    {
        title: "Happy Is England! I Could Be Content",
        author: "John Keats",
        lines: [
            "Happy is England! I could be content",
            "To see no other verdure than its own;",
            "To feel no other breezes than are blown",
            "Through its tall woods with high romances blent;",
            "Yet do I sometimes feel a languishment",
            "For skies Italian, and an inward groan",
            "To sit upon an Alp as on a throne,",
            "And half forget what world or worldling meant.",
            "Happy is England, sweet her artless daughters;",
            "Enough their simple loveliness for me,",
            "Enough their whitest arms in silence clinging;",
            "Yet do I often warmly burn to see",
            "Beauties of deeper glance, and hear their singing,",
            "And float with them about the summer waters."
        ],
        linecount: 14
    },
    {
        title: "To My Brothers",
        author: "John Keats",
        lines: [
            "Small, busy flames play through the fresh-laid coals,",
            "And their faint cracklings o'er our silence creep",
            "Like whispers of the household gods that keep",
            "A gentle empire o'er fraternal souls.",
            "And while for rhymes I search around the poles,",
            "Your eyes are fixed, as in poetic sleep,",
            "Upon the lore so voluble and deep,",
            "That aye at fall of night our care condoles.",
            "This is your birthday, Tom, and I rejoice",
            "That thus it passes smoothly, quietly:",
            "Many such eves of gently whispering noise",
            "May we together pass, and calmly try",
            "What are this world's true joys,—ere the great Voice",
            "From its fair face shall bid our spirits fly."
        ],
        linecount: 14
    },
    {
        title: "A Thing of Beauty (Endymion)",
        author: "John Keats",
        lines: [
            "A thing of beauty is a joy for ever:",
            "Its lovliness increases; it will never",
            "Pass into nothingness; but still will keep",
            "A bower quiet for us, and a sleep",
            "Full of sweet dreams, and health, and quiet breathing.",
            "Therefore, on every morrow, are we wreathing",
            "A flowery band to bind us to the earth,",
            "Spite of despondence, of the inhuman dearth",
            "Of noble natures, of the gloomy days,",
            "Of all the unhealthy and o'er-darkn'd ways",
            "Made for our searching: yes, in spite of all,",
            "Some shape of beauty moves away the pall",
            "From our dark spirits. Such the sun, the moon,",
            "Trees old and young, sprouting a shady boon",
            "For simple sheep; and such are daffodils",
            "With the green world they live in; and clear rills",
            "That for themselves a cooling covert make",
            "'Gainst the hot season; the mid-forest brake,",
            "Rich with a sprinkling of fair musk-rose blooms:",
            "And such too is the grandeur of the dooms",
            "We have imagined for the mighty dead;",
            "An endless fountain of immortal drink,",
            "Pouring unto us from the heaven's brink."
        ],
        linecount: 23
    },
    {
        title: "To Homer",
        author: "John Keats",
        lines: [
            "Standing aloof in giant ignorance,",
            "    Of thee I hear and of the Cyclades,",
            "As one who sits ashore and longs perchance",
            "    To visit dolphin-coral in deep seas.",
            "So thou wast blind;--but then the veil was rent,",
            "    For Jove uncurtain'd Heaven to let thee live,",
            "And Neptune made for thee a spumy tent,",
            "    And Pan made sing for thee his forest-hive;",
            "Aye on the shores of darkness there is light,",
            "    And precipices show untrodden green,",
            "There is a budding morrow in midnight,",
            "    There is a triple sight in blindness keen;",
            "Such seeing hadst thou, as it once befel",
            "To Dian, Queen of Earth, and Heaven, and Hell."
        ],
        linecount: 14
    },
    {
        title: "Give Me Women, Wine, and Snuff",
        author: "John Keats",
        lines: [
            "GIVE me women, wine, and snuff",
            'Until I cry out "hold, enough!"',
            "You may do so sans objection",
            "Till the day of resurrection:",
            "For, bless my beard, they aye shall be",
            "My beloved Trinity."
        ],
        linecount: 6
    },
    {
        title: "To A Friend Who Sent Me Some Roses",
        author: "John Keats",
        lines: [
            "As late I rambled in the happy fields,",
            "What time the skylark shakes the tremulous dew",
            "From his lush clover covert;—when anew",
            "Adventurous knights take up their dinted shields;",
            "I saw the sweetest flower wild nature yields,",
            "A fresh-blown musk-rose; 'twas the first that threw",
            "Its sweets upon the summer: graceful it grew",
            "As is the wand that Queen Titania wields.",
            "And, as I feasted on its fragrancy,",
            "I thought the garden-rose it far excelled;",
            "But when, O Wells! thy roses came to me,",
            "My sense with their deliciousness was spelled:",
            "Soft voices had they, that with tender plea",
            "Whispered of peace, and truth, and friendliness unquelled."
        ],
        linecount: 14
    },
    {
        title: "Written On A Summer Evening",
        author: "John Keats",
        lines: [
            "The church bells toll a melancholy round,",
            "Calling the people to some other prayers,",
            "Some other gloominess, more dreadful cares,",
            "More harkening to the sermon's horrid sound.",
            "Surely the mind of man is closely bound",
            "In some blind spell: seeing that each one tears",
            "Himself from fireside joys and Lydian airs,",
            "And converse high of those with glory crowned.",
            "Still, still they toll, and I should feel a damp,",
            "A chill as from a tomb, did I not know",
            "That they are dying like an outburnt lamp,—",
            "That 'tis their sighing, wailing, ere they go",
            "Into oblivion—that fresh flowers will grow,",
            "And many glories of immortal stamp."
        ],
        linecount: 14
    },
    {
        title: "On First Looking Into Chapman's Homer",
        author: "John Keats",
        lines: [
            "Much have I travell'd in the realms of gold,",
            "    And many goodly states and kingdoms seen;",
            "    Round many western islands have I been",
            "Which bards in fealty to Apollo hold.",
            "Oft of one wide expanse had I been told",
            "    That deep-brow'd Homer ruled as his demesne;",
            "    Yet did I never breathe its pure serene",
            "Till I heard Chapman speak out loud and bold:",
            "Then felt I like some watcher of the skies",
            "    When a new planet swims into his ken;",
            "Or like stout Cortez when with eagle eyes",
            "    He star'd at the Pacific--and all his men",
            "Look'd at each other with a wild surmise--",
            "    Silent, upon a peak in Darien."
        ],
        linecount: 14
    },
    {
        title: "To My Brother George",
        author: "John Keats",
        lines: [
            "Many the wonders I this day have seen:",
            "The sun, when first he kissed away the tears",
            "That filled the eyes of Morn;—the laurelled peers",
            "Who from the feathery gold of evening lean;—",
            "The ocean with its vastness, its blue green,",
            "Its ships, its rocks, its caves, its hopes, its fears,",
            "Its voice mysterious, which whoso hears",
            "Must think on what will be, and what has been.",
            "E'en now, dear George, while this for you I write,",
            "Cynthia is from her silken curtains peeping",
            "So scantly, that it seems her bridal night,",
            "And she her half-discovered revels keeping.",
            "But what, without the social thought of thee,",
            "Would be the wonders of the sky and sea?"
        ],
        linecount: 14
    },
    {
        title: "Stanzas",
        author: "John Keats",
        lines: [
            "IN a drear-nighted December,",
            "   Too happy, happy tree,",
            "Thy branches ne'er remember",
            "   Their green felicity:",
            "The north cannot undo them,",
            "With a sleety whistle through them;",
            "Nor frozen thawings glue them",
            "   From budding at the prime.",
            "",
            "In a drear-nighted December,",
            "   Too happy, happy brook,",
            "Thy bubblings ne'er remember",
            "   Apollo's summer look;",
            "But with a sweet forgetting,",
            "They stay their crystal fretting,",
            "Never, never petting",
            "   About the frozen time.",
            "",
            "Ah! would 'twere so with many",
            "   A gentle girl and boy!",
            "But were there ever any",
            "   Writhed not at passed joy?",
            "To know the change and feel it,",
            "When there is none to heal it,",
            "Nor numbed sense to steal it,",
            "   Was never said in rhyme."
        ],
        linecount: 24
    },
    {
        title: "In Drear-Nighted December",
        author: "John Keats",
        lines: [
            "In drear-nighted December,",
            "Too happy, happy tree,",
            "Thy branches ne'er remember",
            "Their green felicity:",
            "The north cannot undo them",
            "With a sleety whistle through them;",
            "Nor frozen thawings glue them",
            " From budding at the prime.",
            "",
            "In drear-nighted December,",
            "Too happy, happy brook,",
            "Thy bubblings ne'er remember",
            "Apollo's summer look;",
            "But with a sweet forgetting,",
            "They stay their crystal fretting,",
            "Never, never petting",
            "About the frozen time.",
            "",
            "Ah! would 'twere so with many",
            "A gentle girl and boy!",
            "But were there ever any",
            "Writhed not at passed joy?",
            "The feel of not to feel it,",
            "When there is none to heal it",
            "Nor numbed sense to steel it,",
            "Was never said in rhyme."
        ],
        linecount: 24
    },
    {
        title: "Bright Star, Would I Were Steadfast As Thou Art",
        author: "John Keats",
        lines: [
            "Bright star, would I were steadfast as thou art—",
            "    Not in lone splendour hung aloft the night",
            "And watching, with eternal lids apart,",
            "    Like nature's patient, sleepless Eremite,",
            "The moving waters at their priestlike task",
            "    Of pure ablution round earth's human shores,",
            "Or gazing on the new soft-fallen mask",
            "    Of snow upon the mountains and the moors—",
            "No—yet still steadfast, still unchangeable,",
            "    Pillow'd upon my fair love's ripening breast,",
            "To feel for ever its soft fall and swell,",
            "    Awake for ever in a sweet unrest,",
            "Still, still to hear her tender-taken breath,",
            "And so live ever—or else swoon to death."
        ],
        linecount: 14
    },
    {
        title: "Ode To Autumn",
        author: "John Keats",
        lines: [
            "Season of mists and mellow fruitfulness,",
            "Close bosom-friend of the maturing sun;",
            "Conspiring with him how to load and bless",
            "With fruit the vines that round the thatch-eaves run;",
            "To bend with apples the mossed cottage-trees,",
            "And fill all fruit with ripeness to the core;",
            "To swell the gourd, and plump the hazel shells",
            "With a sweet kernel; to set budding more,",
            "And still more, later flowers for the bees,",
            "Until they think warm days will never cease,",
            "For Summer has o'er-brimmed their clammy cell.",
            "",
            "Who hath not seen thee oft amid thy store?",
            "Sometimes whoever seeks abroad may find",
            "Thee sitting careless on a granary floor,",
            "Thy hair soft-lifted by the winnowing wind;",
            "Or on a half-reaped furrow sound asleep,",
            "Drowsed with the fume of poppies, while thy hook",
            "Spares the next swath and all its twined flowers;",
            "And sometimes like a gleaner thou dost keep",
            "Steady thy laden head across a brook;",
            "Or by a cider-press, with patient look,",
            "Thou watchest the last oozings, hours by hours.",
            "",
            "Where are the songs of Spring? Ay, where are they?",
            "Think not of them, thou hast thy music too,---",
            "While barred clouds bloom the soft-dying day,",
            "And touch the stubble-plains with rosy hue;",
            "Then in a wailful choir, the small gnats mourn",
            "Among the river sallows, borne aloft",
            "Or sinking as the light wind lives or dies;",
            "And full-grown lambs loud bleat from hilly bourn;",
            "Hedge-crickets sing; and now with treble soft",
            "The redbreast whistles from a garden-croft,",
            "And gathering swallows twitter in the skies."
        ],
        linecount: 33
    }
];
