export const poems = [
  {
    author: "Yeats, William Butler",
    lines: [
      "TURNING and turning in the widening gyre",
      "The falcon cannot hear the falconer;",
      "Things fall apart; the centre cannot hold;",
      "Mere anarchy is loosed upon the world,",
      "The blood-dimmed tide is loosed, and everywhere",
      "The ceremony of innocence is drowned;",
      "The best lack all conviction, while the worst",
      "Are full of passionate intensity.",
      "Surely some revelation is at hand;",
      "Surely the Second Coming is at hand.",
      "The Second Coming! Hardly are those words out",
      "When a vast image out of Spiritus Mundi",
      "Troubles my sight:  somewhere in sands of the desert",
      "A shape with lion body and the head of a man,",
      "A gaze blank and pitiless as the sun,",
      "Is moving its slow thighs, while all about it",
      "Reel shadows of the indignant desert birds.",
      "The darkness drops again; but now I know",
      "That twenty centuries of stony sleep",
      "Were vexed to nightmare by a rocking cradle,",
      "And what rough beast, its hour come round at last,",
      "Slouches towards Bethlehem to be born?",
    ],
    title: "The Second Coming",
  },
  {
    author: "Yeats, William Butler",
    lines: [
      "A sudden blow: the great wings beating still",
      "Above the staggering girl, her thighs caressed",
      "By the dark webs, her nape caught in his bill,",
      "He holds her helpless breast upon his breast.",
      "",
      "How can those terrified vague fingers push",
      "The feathered glory from her loosening thighs?",
      "And how can body, laid in that white rush,",
      "But feel the strange heart beating where it lies?",
      "",
      "A shudder in the loins engenders there",
      "The broken wall, the burning roof and tower",
      "And Agamemnon dead.",
      "                                  Being so caught up,",
      "So mastered by the brute blood of the air,",
      "Did she put on his knowledge with his power",
      "Before the indifferent beak could let her drop?",
    ],
    title: "Leda and the Swan",
  },
];
