export const sonnets = [
  {
    title: "SONNET 1",
    lines: [
      "From fairest creatures we desire increase,",
      "That thereby beauty's rose might never die,",
      "But as the riper should by time decease,",
      "His tender heir might bear his memory:",
      "But thou, contracted to thine own bright eyes,",
      "Feed'st thy light'st flame with self-substantial fuel,",
      "Making a famine where abundance lies",
      "Thyself thy foe, to thy sweet self too cruel.",
      "Thou that art now the world's fresh ornament",
      "And only herald to the gaudy spring,",
      "Within thine own bud buriest thy content",
      "And, tender churl, makest waste in niggarding.",
      "Pity the world, or else this glutton be,",
      "To eat the world's due, by the grave and thee.",
    ],
  },
  {
    title: "SONNET 2",
    lines: [
      "When forty winters shall beseige thy brow,",
      "And dig deep trenches in thy beauty's field,",
      "Thy youth's proud livery, so gazed on now,",
      "Will be a tatter'd weed, of small worth held:",
      "Then being ask'd where all thy beauty lies,",
      "Where all the treasure of thy lusty days,",
      "To say, within thine own deep-sunken eyes",
      "Were an all-eating shame and thriftless praise.",
      "How much more praise deserved thy beauty's use,",
      "If thou couldst answer 'This fair child of mine",
      "Shall sum my count and make my old excuse,'",
      "Proving his beauty by succession thine!",
      "This were to be new made when thou art old,",
      "And see thy blood warm when thou feel'st it cold.",
    ],
  },
  {
    title: "SONNET 3",
    lines: [
      "Look in thy glass, and tell the face thou viewest",
      "Now is the time that face should form another;",
      "Whose fresh repair if now thou not renewest,",
      "Thou dost beguile the world, unbless some mother.",
      "For where is she so fair whose unear'd womb",
      "Disdains the tillage of thy husbandry?",
      "Or who is he so fond will be the tom",
      "Of his self-love, to stop posterity?",
      "Thou art thy mother's glass, and she in thee",
      "Calls back the lovely April of her prime:",
      "So thou through windows of thine age shall see",
      "Despite of wrinkles this thy golden time.",
      "But if thou live, remember'd not to be,",
      "Die single, and thine image dies with thee.",
    ],
  },
  {
    title: "SONNET 4",
    lines: [
      "Unthrifty loveliness, why dost thou spend",
      "Upon thyself thy beauty's legacy?",
      "Nature's bequest gives nothing but doth lend,",
      "And being frank she lends to those are free.",
      "Then, beauteous niggard, why dost thou abuse",
      "The bounteous largess given thee to give?",
      "Profitless usurer, why dost thou us",
      "So great a sum of sums, yet canst not live?",
      "For having traffic with thyself alone,",
      "Thou of thyself thy sweet self dost deceive.",
      "Then how, when nature calls thee to be gone,",
      "What acceptable audit canst thou leave?",
      "Thy unused beauty must be tomb'd with thee,",
      "Which, used, lives th' executor to be.",
    ],
  },
  {
    title: "SONNET 5",
    lines: [
      "Those hours, that with gentle work did frame",
      "The lovely gaze where every eye doth dwell,",
      "Will play the tyrants to the very same",
      "And that unfair which fairly doth excel:",
      "For never-resting time leads summer on",
      "To hideous winter and confounds him there;",
      "Sap cheque'd with frost and lusty leaves qu',te gone",
      "Beauty o'ersnow'd and bareness every where:",
      "Then, were not summer's distillation left,",
      "A liquid prisoner pent in walls of glass,",
      "Beauty's effect with beauty were bereft,",
      "Nor it nor no remembrance what it was:",
      "But flowers distill'd though they with winter meet,",
      "Leese but their show; their substance still lives sweet.",
    ],
  },
  {
    title: "SONNET 6",
    lines: [
      "Then let not winter's ragged hand deface",
      "In thee thy summer, ere thou be distill'd:",
      "Make sweet some vial; treasure thou some place",
      "With beauty's treasure, ere it be self-kill'd.",
      "That use is not forbidden usury,",
      "Which happies those that pay the willing loan;",
      "That's for thyself to breed another thee",
      "Or ten times happier, be it ten for one;",
      "Ten times thyself were happier than thou art,",
      "If ten of thine ten times refigured thee:",
      "Then what could death do, if thou shouldst depart,",
      "Leaving thee living in posterity?",
      "Be not self-will'd, for thou art much too fair",
      "To be death's conquest and make worms thine heir.",
    ],
  },
  {
    title: "SONNET 7",
    lines: [
      "Lo! in the orient when the gracious light",
      "Lifts up his burning head, each under eye",
      "Doth homage to his new-appearing sight,",
      "Serving with looks his sacred majesty;",
      "And having climb'd the steep-up heavenly hill,",
      "Resembling strong youth in his middle age,",
      "yet mortal looks adore his beauty still",
      "Attending on his golden pilgrimage;",
      "But when from highmost pitch, with weary car,",
      "Like feeble age, he reeleth from the day,",
      "The eyes, 'fore duteous, now converted are",
      "From his low tract and look another way:",
      "So thou, thyself out-going in thy noon,",
      "Unlook'd on diest, unless thou get a son.",
    ],
  },
  {
    title: "SONNET 8",
    lines: [
      "Music to hear, why hear'st thou music sadly?",
      "Sweets with sweets war not, joy delights in joy.",
      "Why lovest thou that which thou receivest not gladly,",
      "Or else receivest with pleasure thine annoy?",
      "If the true concord of well-tuned sounds,",
      "By unions married, do offend thine ear,",
      "They do but sweetly chide thee, who confunds",
      "In singleness the parts that thou shouldst bear.",
      "Mark how one string, sweet husband to another,",
      "Strikes each in each by mutual ordering,",
      "Resembling sire and child and happy mother",
      "Who all in one, one pleasing note do sing:",
      "Whose speechless song, being many, seeming one,",
      "Sings this to thee: 'thou single wilt prove none.'",
    ],
  },
  {
    title: "SONNET 9",
    lines: [
      "Is it for fear to wet a widow's eye",
      "That thou consumest thyself in single life?",
      "Ah! if thou issueless shalt hap to die.",
      "The world will wail thee, like a makeless wife;",
      "The world will be thy widow and still weep",
      "That thou no form of thee hast left behind,",
      "When every private widow well may kee",
      "By children's eyes her husband's shape in mind.",
      "Look, what an unthrift in the world doth spend",
      "Shifts but his place, for still the world enjoys it;",
      "But beauty's waste hath in the world an end,",
      "And kept unused, the user so destroys it.",
      "No love toward others in that bosom sits",
      "That on himself such murderous shame commits.",
    ],
  },
  {
    title: "SONNET 10",
    lines: [
      "For shame! deny that thou bear'st love to any,",
      "Who for thyself art so unprovident.",
      "Grant, if thou wilt, thou art beloved of many,",
      "But that thou none lovest is most evident;",
      "For thou art so possess'd with murderous hate",
      "That 'gainst thyself thou stick'st not to conspire.",
      "Seeking that beauteous roof to ruinat",
      "Which to repair should be thy chief desire., change thy thought, that I may change my mind!",
      "Shall hate be fairer lodged than gentle love?",
      "Be, as thy presence is, gracious and kind,",
      "Or to thyself at least kind-hearted prove:",
      "    Make thee another self, for love of me,",
      "That beauty still may live in thine or thee.'",
    ],
  },
  {
    title: "SONNET 11",
    lines: [
      "As fast as thou shalt wane, so fast thou growest",
      "In one of thine, from that which thou departest;",
      "And that fresh blood which youngly thou bestowest",
      "Thou mayst call thine when thou from youth convertest.",
      "Herein lives wisdom, beauty and increase:",
      "Without this, folly, age and cold decay:",
      "If all were minded so, the times should case",
      "And threescore year would make the world away.",
      "Let those whom Nature hath not made for store,",
      "Harsh featureless and rude, barrenly perish:",
      "Look, whom she best endow'd she gave the more;",
      "Which bounteous gift thou shouldst in bounty cherish:",
      "She carved thee for her seal, and meant thereby",
      "Thou shouldst print more, not let that copy die.",
    ],
  },
  {
    title: "SONNET 12",
    lines: [
      "When I do count the clock that tells the time,",
      "And see the brave day sunk in hideous night;",
      "When I behold the violet past prime,",
      "And sable curls all silver'd o'er with white;",
      "When lofty trees I see barren of leaves",
      "Which erst from heat did canopy the herd,",
      "And summer's green all girded up in sheave",
      "Borne on the bier with white and bristly beard,",
      "Then of thy beauty do I question make,",
      "That thou among the wastes of time must go,",
      "Since sweets and beauties do themselves forsake",
      "And die as fast as they see others grow;",
      "And nothing 'gainst Time's scythe can make defence",
      "Save breed, to brave him when he takes thee hence.",
    ],
  },
  {
    title: "SONNET 14",
    lines: [
      "Not from the stars do I my judgment pluck;",
      "And yet methinks I have astronomy,",
      "But not to tell of good or evil luck,",
      "Of plagues, of dearths, or seasons' quality;",
      "Nor can I fortune to brief minutes tell,",
      "Pointing to each his thunder, rain and wind,",
      "Or say with princes if it shall go well",
      "By oft predict that I in heaven find:",
      "But from thine eyes my knowledge I derive,",
      "And, constant stars, in them I read such art",
      "As truth and beauty shall together thrive,",
      "If from thyself to store thou wouldst convert;",
      "Or else of thee this I prognosticate:",
      "Thy end is truth's and beauty's doom and date.",
    ],
  },
  {
    title: "SONNET 1",
    lines: [
      "When I consider every thing that grows",
      "Holds in perfection but a little moment,",
      "That this huge stage presenteth nought but shows",
      "Whereon the stars in secret influence comment;",
      "When I perceive that men as plants increase,",
      "Cheered and cheque'd even by the self-same sky,",
      "Vaunt in their youthful sap, at height decrease",
      "And wear their brave state out of memory;",
      "Then the conceit of this inconstant stay",
      "Sets you most rich in youth before my sight,",
      "Where wasteful Time debateth with Decay,",
      "To change your day of youth to sullied night;",
      "And all in war with Time for love of you,",
      "As he takes from you, I engraft you new.",
    ],
  },
  {
    title: "SONNET 16",
    lines: [
      "But wherefore do not you a mightier way",
      "Make war upon this bloody tyrant, Time?",
      "And fortify yourself in your decay",
      "With means more blessed than my barren rhyme?",
      "Now stand you on the top of happy hours,",
      "And many maiden gardens yet unset",
      "With virtuous wish would bear your,living flowers,",
      "Much liker than your painted counterfeit:",
      "So should the lines of life that life repair,",
      "Which this, Time's pencil, or my pupil pen,",
      "Neither in inward worth nor outward fair,",
      "Can make you live yourself in eyes of men.",
      "To give away yourself keeps yourself still,",
      "And you must live, drawn by your own sweet skill.",
    ],
  },
  {
    title: "SONNET 17",
    lines: [
      "Who will believe my verse in time to come,",
      "If it were fill'd with your most high deserts?",
      "Though yet, heaven knows, it is but as a tomb",
      "Which hides your life and shows not half your parts.",
      "If I could write the beauty of your eyes",
      "And in fresh numbers number all your graces,",
      "The age to come would say 'This poet lies",
      "Such heavenly touches ne'er touch'd earthly faces.'",
      "So should my papers yellow'd with their age",
      "Be scorn'd like old men of less truth than tongue,",
      "And your true rights be term'd a poet's rage",
      "And stretched metre of an antique song:",
      "But were some child of yours alive that time,",
      "You should live twice; in it and in my rhyme.",
    ],
  },
  {
    title: "SONNET 18",
    lines: [
      "Shall I compare thee to a summer's day?",
      "Thou art more lovely and more temperate:",
      "Rough winds do shake the darling buds of May,",
      "And summer's lease hath all too short a date:",
      "Sometime too hot the eye of heaven shines,",
      "And often is his gold complexion dimm'd;",
      "And every fair from fair sometime decline",
      "By chance or nature's changing course untrimm'd;",
      "But thy eternal summer shall not fade",
      "Nor lose possession of that fair thou owest;",
      "Nor shall Death brag thou wander'st in his shade,",
      "When in eternal lines to time thou growest:",
      "So long as men can breathe or eyes can see,",
      "So long lives this and this gives life to thee.'",
    ],
  },
  {
    title: "SONNET 19",
    lines: [
      "Devouring Time, blunt thou the lion's paws,",
      "And make the earth devour her own sweet brood;",
      "Pluck the keen teeth from the fierce tiger's jaws,",
      "And burn the long-lived phoenix in her blood;",
      "Make glad and sorry seasons as thou fleets,",
      "And do whate'er thou wilt, swift-footed Time,",
      "To the wide world and all her fading sweets",
      "But I forbid thee one most heinous crime: , carve not with thy hours my love's fair brow,",
      "Nor draw no lines there with thine antique pen;",
      "Him in thy course untainted do allow",
      "For beauty's pattern to succeeding men.",
      "    Yet, do thy worst, old Time: despite thy wrong,",
      "My love shall in my verse ever live young.'",
    ],
  },
  {
    title: "SONNET 20",
    lines: [
      "A woman's face with Nature's own hand painted",
      "Hast thou, the master-mistress of my passion;",
      "A woman's gentle heart, but not acquainted",
      "With shifting change, as is false women's fashion;",
      "An eye more bright than theirs, less false in rolling,",
      "Gilding the object whereupon it gazeth;",
      "A man in hue, all 'hues' in his controllng,",
      "Much steals men's eyes and women's souls amazeth.",
      "And for a woman wert thou first created;",
      "Till Nature, as she wrought thee, fell a-doting,",
      "And by addition me of thee defeated,",
      "By adding one thing to my purpose nothing.",
      "But since she prick'd thee out for women's pleasure,",
      "Mine be thy love and thy love's use their treasure.",
    ],
  },
  {
    title: "SONNET 21",
    lines: [
      "So is it not with me as with that Muse",
      "Stirr'd by a painted beauty to his verse,",
      "Who heaven itself for ornament doth use",
      "And every fair with his fair doth rehearse",
      "Making a couplement of proud compare,",
      "With sun and moon, with earth and sea's rich gems,",
      "With April's first-born flowers, and all things rar",
      "That heaven's air in this huge rondure hems.",
      "let me, true in love, but truly write,",
      "And then believe me, my love is as fair",
      "As any mother's child, though not so bright",
      "As those gold candles fix'd in heaven's air:",
      "    Let them say more than like of hearsay well;",
      "I will not praise that purpose not to sell.'",
    ],
  },
  {
    title: "SONNET 22",
    lines: [
      "My glass shall not persuade me I am old,",
      "So long as youth and thou are of one date;",
      "But when in thee time's furrows I behold,",
      "Then look I death my days should expiate.",
      "For all that beauty that doth cover thee",
      "Is but the seemly raiment of my heart,",
      "Which in thy breast doth live, as thine', in me:",
      "How can I then be elder than thou art?, therefore, love, be of thyself so wary",
      "As I, not for myself, but for thee will;",
      "Bearing thy heart, which I will keep so chary",
      "As tender nurse her babe from faring ill.",
      "    Presume not on thy heart when mine is slain;",
      "Thou gavest me thine, not to give back again.'",
    ],
  },
  {
    title: "SONNET 26",
    lines: [
      "Lord of my love, to whom in vassalage",
      "Thy merit hath my duty strongly knit,",
      "To thee I send this written embassage,",
      "To witness duty, not to show my wit:",
      "Duty so great, which wit so poor as mine",
      "May make seem bare, in wanting words to show it,",
      "But that I hope some good conceit of thin",
      "In thy soul's thought, all naked, will bestow it;",
      "Till whatsoever star that guides my moving",
      "Points on me graciously with fair aspect",
      "And puts apparel on my tatter'd loving,",
      "To show me worthy of thy sweet respect:",
      "Then may I dare to boast how I do love thee;",
      "Till then not show my head where thou mayst prove me.",
    ],
  },
  {
    title: "SONNET 29",
    lines: [
      "When, in disgrace with fortune and men's eyes,",
      "I all alone beweep my outcast state",
      "And trouble deaf heaven with my bootless cries",
      "And look upon myself and curse my fate,",
      "Wishing me like to one more rich in hope,",
      "Featured like him, like him with friends possess'd,",
      "Desiring this man's art and that man's scope",
      "With what I most enjoy contented least;",
      "Yet in these thoughts myself almost despising,",
      "Haply I think on thee, and then my state,",
      "Like to the lark at break of day arising",
      "From sullen earth, sings hymns at heaven's gate;",
      "For thy sweet love remember'd such wealth brings",
      "That then I scorn to change my state with kings.",
    ],
  },
  {
    title: "SONNET 30",
    lines: [
      "When to the sessions of sweet silent thought",
      "I summon up remembrance of things past,",
      "I sigh the lack of many a thing I sought,",
      "And with old woes new wail my dear time's waste:",
      "Then can I drown an eye, unused to flow,",
      "For precious friends hid in death's dateless night,",
      "And weep afresh love's long since cancell'd woe",
      "And moan the expense of many a vanish'd sight:",
      "Then can I grieve at grievances foregone,",
      "And heavily from woe to woe tell o'er",
      "The sad account of fore-bemoaned moan,",
      "Which I new pay as if not paid before.",
      "But if the while I think on thee, dear friend,",
      "All losses are restored and sorrows end.",
    ],
  },
  {
    title: "SONNET 34",
    lines: [
      "Why didst thou promise such a beauteous day,",
      "And make me travel forth without my cloak,",
      "To let base clouds o'ertake me in my way,",
      "Hiding thy bravery in their rotten smoke?",
      "'Tis not enough that through the cloud thou break,",
      "To dry the rain on my storm-beaten face,",
      "For no man well of such a salve can spea",
      "That heals the wound and cures not the disgrace:",
      "Nor can thy shame give physic to my grief;",
      "Though thou repent, yet I have still the loss:",
      "The offender's sorrow lends but weak relief",
      "To him that bears the strong offence's cross.",
      "Ah! but those tears are pearl which thy love sheds,",
      "And they are rich and ransom all ill deeds.",
    ],
  },
  {
    title: "SONNET 36",
    lines: [
      "Let me confess that we two must be twain,",
      "Although our undivided loves are one:",
      "So shall those blots that do with me remain",
      "Without thy help by me be borne alone.",
      "In our two loves there is but one respect,",
      "Though in our lives a separable spite,",
      "Which though it alter not love's sole effect",
      "Yet doth it steal sweet hours from love's delight.",
      "I may not evermore acknowledge thee,",
      "Lest my bewailed guilt should do thee shame,",
      "Nor thou with public kindness honour me,",
      "Unless thou take that honour from thy name:",
      "But do not so; I love thee in such sort",
      "As, thou being mine, mine is thy good report.",
    ],
  },
  {
    title: "SONNET 37",
    lines: [
      "As a decrepit father takes delight",
      "To see his active child do deeds of youth,",
      "So I, made lame by fortune's dearest spite,",
      "Take all my comfort of thy worth and truth.",
      "For whether beauty, birth, or wealth, or wit,",
      "Or any of these all, or all, or more,",
      "Entitled in thy parts do crowned sit",
      "I make my love engrafted to this store:",
      "So then I am not lame, poor, nor despised,",
      "Whilst that this shadow doth such substance give",
      "That I in thy abundance am sufficed",
      "And by a part of all thy glory live.",
      "Look, what is best, that best I wish in thee:",
      "This wish I have; then ten times happy me!",
    ],
  },
  {
    title: "SONNET 38",
    lines: [
      "How can my Muse want subject to invent,",
      "While thou dost breathe, that pour'st into my verse",
      "Thine own sweet argument, too excellent",
      "For every vulgar paper to rehearse?, give thyself the thanks, if aught in me",
      "Worthy perusal stand against thy sight;",
      "For who's so dumb that cannot write to thee,",
      "When thou thyself dost give invention light",
      "Be thou the tenth Muse, ten times more in worth",
      "Than those old nine which rhymers invocate;",
      "And he that calls on thee, let him bring forth",
      "Eternal numbers to outlive long date.",
      "    If my slight Muse do please these curious days,",
      "The pain be mine, but thine shall be the praise.'",
    ],
  },
  {
    title: "SONNET 39",
    lines: [
      "O, how thy worth with manners may I sing,",
      "When thou art all the better part of me?",
      "What can mine own praise to mine own self bring?",
      "And what is 't but mine own when I praise thee?",
      "Even for this let us divided live,",
      "And our dear love lose name of single one,",
      "That by this separation I may giv",
      "That due to thee which thou deservest alone. absence, what a torment wouldst thou prove,",
      "Were it not thy sour leisure gave sweet leave",
      "To entertain the time with thoughts of love,",
      "Which time and thoughts so sweetly doth deceive,",
      "    And that thou teachest how to make one twain,",
      "By praising him here who doth hence remain!'",
    ],
  },
  {
    title: "SONNET 40",
    lines: [
      "Take all my loves, my love, yea, take them all;",
      "What hast thou then more than thou hadst before?",
      "No love, my love, that thou mayst true love call;",
      "All mine was thine before thou hadst this more.",
      "Then if for my love thou my love receivest,",
      "I cannot blame thee for my love thou usest;",
      "But yet be blamed, if thou thyself deceives",
      "By wilful taste of what thyself refusest.",
      "I do forgive thy robbery, gentle thief,",
      "Although thou steal thee all my poverty;",
      "And yet, love knows, it is a greater grief",
      "To bear love's wrong than hate's known injury.",
      "Lascivious grace, in whom all ill well shows,",
      "Kill me with spites; yet we must not be foes.",
    ],
  },
  {
    title: "SONNET 41",
    lines: [
      "Those petty wrongs that liberty commits,",
      "When I am sometime absent from thy heart,",
      "Thy beauty and thy years full well befits,",
      "For still temptation follows where thou art.",
      "Gentle thou art and therefore to be won,",
      "Beauteous thou art, therefore to be assailed;",
      "And when a woman woos, what woman's so",
      "Will sourly leave her till she have prevailed?",
      "Ay me! but yet thou mightest my seat forbear,",
      "And chide try beauty and thy straying youth,",
      "Who lead thee in their riot even there",
      "Where thou art forced to break a twofold truth,",
      "Hers by thy beauty tempting her to thee,",
      "Thine, by thy beauty being false to me.",
    ],
  },
  {
    title: "SONNET 42",
    lines: [
      "That thou hast her, it is not all my grief,",
      "And yet it may be said I loved her dearly;",
      "That she hath thee, is of my wailing chief,",
      "A loss in love that touches me more nearly.",
      "Loving offenders, thus I will excuse ye:",
      "Thou dost love her, because thou knowst I love her;",
      "And for my sake even so doth she abuse me",
      "Suffering my friend for my sake to approve her.",
      "If I lose thee, my loss is my love's gain,",
      "And losing her, my friend hath found that loss;",
      "Both find each other, and I lose both twain,",
      "And both for my sake lay on me this cross:",
      "But here's the joy; my friend and I are one;",
      "Sweet flattery! then she loves but me alone.",
    ],
  },
  {
    title: "SONNET 43",
    lines: [
      "When most I wink, then do mine eyes best see,",
      "For all the day they view things unrespected;",
      "But when I sleep, in dreams they look on thee,",
      "And darkly bright are bright in dark directed.",
      "Then thou, whose shadow shadows doth make bright,",
      "How would thy shadow's form form happy show",
      "To the clear day with thy much clearer light",
      "When to unseeing eyes thy shade shines so!",
      "How would, I say, mine eyes be blessed made",
      "By looking on thee in the living day,",
      "When in dead night thy fair imperfect shade",
      "Through heavy sleep on sightless eyes doth stay!",
      "All days are nights to see till I see thee,",
      "And nights bright days when dreams do show thee me.",
    ],
  },
  {
    title: "SONNET 47",
    lines: [
      "Betwixt mine eye and heart a league is took,",
      "And each doth good turns now unto the other:",
      "When that mine eye is famish'd for a look,",
      "Or heart in love with sighs himself doth smother,",
      "With my love's picture then my eye doth feast",
      "And to the painted banquet bids my heart;",
      "Another time mine eye is my heart's gues",
      "And in his thoughts of love doth share a part:",
      "So, either by thy picture or my love,",
      "Thyself away art resent still with me;",
      "For thou not farther than my thoughts canst move,",
      "And I am still with them and they with thee;",
      "Or, if they sleep, thy picture in my sight",
      "Awakes my heart to heart's and eye's delight.",
    ],
  },
  {
    title: "SONNET 48",
    lines: [
      "How careful was I, when I took my way,",
      "Each trifle under truest bars to thrust,",
      "That to my use it might unused stay",
      "From hands of falsehood, in sure wards of trust!",
      "But thou, to whom my jewels trifles are,",
      "Most worthy of comfort, now my greatest grief,",
      "Thou, best of dearest and mine only care",
      "Art left the prey of every vulgar thief.",
      "Thee have I not lock'd up in any chest,",
      "Save where thou art not, though I feel thou art,",
      "Within the gentle closure of my breast,",
      "From whence at pleasure thou mayst come and part;",
      "And even thence thou wilt be stol'n, I fear,",
      "For truth proves thievish for a prize so dear.",
    ],
  },
  {
    title: "SONNET 49",
    lines: [
      "Against that time, if ever that time come,",
      "When I shall see thee frown on my defects,",
      "When as thy love hath cast his utmost sum,",
      "Call'd to that audit by advised respects;",
      "Against that time when thou shalt strangely pass",
      "And scarcely greet me with that sun thine eye,",
      "When love, converted from the thing it was",
      "Shall reasons find of settled gravity,--",
      "Against that time do I ensconce me here",
      "Within the knowledge of mine own desert,",
      "And this my hand against myself uprear,",
      "To guard the lawful reasons on thy part:",
      "To leave poor me thou hast the strength of laws,",
      "Since why to love I can allege no cause.",
    ],
  },
  {
    title: "SONNET 50",
    lines: [
      "How heavy do I journey on the way,",
      "When what I seek, my weary travel's end,",
      "Doth teach that ease and that repose to say",
      "'Thus far the miles are measured from thy friend!'",
      "The beast that bears me, tired with my woe,",
      "Plods dully on, to bear that weight in me,",
      "As if by some instinct the wretch did kno",
      "His rider loved not speed, being made from thee:",
      "The bloody spur cannot provoke him on",
      "That sometimes anger thrusts into his hide;",
      "Which heavily he answers with a groan,",
      "More sharp to me than spurring to his side;",
      "For that same groan doth put this in my mind;",
      "My grief lies onward and my joy behind.",
    ],
  },
  {
    title: "SONNET 52",
    lines: [
      "So am I as the rich, whose blessed key",
      "Can bring him to his sweet up-locked treasure,",
      "The which he will not every hour survey,",
      "For blunting the fine point of seldom pleasure.",
      "Therefore are feasts so solemn and so rare,",
      "Since, seldom coming, in the long year set,",
      "Like stones of worth they thinly placed are",
      "Or captain jewels in the carcanet.",
      "So is the time that keeps you as my chest,",
      "Or as the wardrobe which the robe doth hide,",
      "To make some special instant special blest,",
      "By new unfolding his imprison'd pride.",
      "Blessed are you, whose worthiness gives scope,",
      "Being had, to triumph, being lack'd, to hope.",
    ],
  },
  {
    title: "SONNET 53",
    lines: [
      "What is your substance, whereof are you made,",
      "That millions of strange shadows on you tend?",
      "Since every one hath, every one, one shade,",
      "And you, but one, can every shadow lend.",
      "Describe Adonis, and the counterfeit",
      "Is poorly imitated after you;",
      "On Helen's cheek all art of beauty set,",
      "And you in Grecian tires are painted new:",
      "Speak of the spring and foison of the year;",
      "The one doth shadow of your beauty show,",
      "The other as your bounty doth appear;",
      "And you in every blessed shape we know.",
      "In all external grace you have some part,",
      "But you like none, none you, for constant heart.",
    ],
  },
  {
    title: "SONNET 54",
    lines: [
      "O, how much more doth beauty beauteous seem",
      "By that sweet ornament which truth doth give!",
      "The rose looks fair, but fairer we it deem",
      "For that sweet odour which doth in it live.",
      "The canker-blooms have full as deep a dye",
      "As the perfumed tincture of the roses,",
      "Hang on such thorns and play as wantonl",
      "When summer's breath their masked buds discloses:",
      "But, for their virtue only is their show,",
      "They live unwoo'd and unrespected fade,",
      "Die to themselves. Sweet roses do not so;",
      "Of their sweet deaths are sweetest odours made:",
      "And so of you, beauteous and lovely youth,",
      "When that shall fade, my verse distills your truth.",
    ],
  },
  {
    title: "SONNET 56",
    lines: [
      "Sweet love, renew thy force; be it not said",
      "Thy edge should blunter be than appetite,",
      "Which but to-day by feeding is allay'd,",
      "To-morrow sharpen'd in his former might:",
      "So, love, be thou; although to-day thou fill",
      "Thy hungry eyes even till they wink with fullness,",
      "To-morrow see again, and do not kil",
      "The spirit of love with a perpetual dullness.",
      "Let this sad interim like the ocean be",
      "Which parts the shore, where two contracted new",
      "Come daily to the banks, that, when they see",
      "Return of love, more blest may be the view;",
      "Else call it winter, which being full of care",
      "Makes summer's welcome thrice more wish'd, more rare.",
    ],
  },
  {
    title: "SONNET 57",
    lines: [
      "Being your slave, what should I do but tend",
      "Upon the hours and times of your desire?",
      "I have no precious time at all to spend,",
      "Nor services to do, till you require.",
      "Nor dare I chide the world-without-end hour",
      "Whilst I, my sovereign, watch the clock for you,",
      "Nor think the bitterness of absence sou",
      "When you have bid your servant once adieu;",
      "Nor dare I question with my jealous thought",
      "Where you may be, or your affairs suppose,",
      "But, like a sad slave, stay and think of nought",
      "Save, where you are how happy you make those.",
      "So true a fool is love that in your will,",
      "Though you do any thing, he thinks no ill.",
    ],
  },
  {
    title: "SONNET 59",
    lines: [
      "If there be nothing new, but that which is",
      "Hath been before, how are our brains beguiled,",
      "Which, labouring for invention, bear amiss",
      "The second burden of a former child!, that record could with a backward look,",
      "Even of five hundred courses of the sun,",
      "Show me your image in some antique book,",
      "Since mind at first in character was done",
      "That I might see what the old world could say",
      "To this composed wonder of your frame;",
      "Whether we are mended, or whether better they,",
      "Or whether revolution be the same.",
      "    O, sure I am, the wits of former days",
      "To subjects worse have given admiring praise.'",
    ],
  },
  {
    title: "SONNET 60",
    lines: [
      "Like as the waves make towards the pebbled shore,",
      "So do our minutes hasten to their end;",
      "Each changing place with that which goes before,",
      "In sequent toil all forwards do contend.",
      "Nativity, once in the main of light,",
      "Crawls to maturity, wherewith being crown'd,",
      "Crooked elipses 'gainst his glory fight",
      "And Time that gave doth now his gift confound.",
      "Time doth transfix the flourish set on youth",
      "And delves the parallels in beauty's brow,",
      "Feeds on the rarities of nature's truth,",
      "And nothing stands but for his scythe to mow:",
      "And yet to times in hope my verse shall stand,",
      "Praising thy worth, despite his cruel hand.",
    ],
  },
  {
    title: "SONNET 63",
    lines: [
      "Against my love shall be, as I am now,",
      "With Time's injurious hand crush'd and o'er-worn;",
      "When hours have drain'd his blood and fill'd his brow",
      "With lines and wrinkles; when his youthful morn",
      "Hath travell'd on to age's steepy night,",
      "And all those beauties whereof now he's king",
      "Are vanishing or vanish'd out of sight",
      "Stealing away the treasure of his spring;",
      "For such a time do I now fortify",
      "Against confounding age's cruel knife,",
      "That he shall never cut from memory",
      "My sweet love's beauty, though my lover's life:",
      "His beauty shall in these black lines be seen,",
      "And they shall live, and he in them still green.",
    ],
  },
  {
    title: "SONNET 64",
    lines: [
      "When I have seen by Time's fell hand defaced",
      "The rich proud cost of outworn buried age;",
      "When sometime lofty towers I see down-razed",
      "And brass eternal slave to mortal rage;",
      "When I have seen the hungry ocean gain",
      "Advantage on the kingdom of the shore,",
      "And the firm soil win of the watery mai",
      "Increasing store with loss and loss with store;",
      "When I have seen such interchange of state,",
      "Or state itself confounded to decay;",
      "Ruin hath taught me thus to ruminate,",
      "That Time will come and take my love away.",
      "This thought is as a death, which cannot choose",
      "But weep to have that which it fears to lose.",
    ],
  },
  {
    title: "SONNET 67",
    lines: [
      "Ah! wherefore with infection should he live,",
      "And with his presence grace impiety,",
      "That sin by him advantage should achieve",
      "And lace itself with his society?",
      "Why should false painting imitate his cheek",
      "And steal dead seeing of his living hue?",
      "Why should poor beauty indirectly see",
      "Roses of shadow, since his rose is true?",
      "Why should he live, now Nature bankrupt is,",
      "Beggar'd of blood to blush through lively veins?",
      "For she hath no exchequer now but his,",
      "And, proud of many, lives upon his gains.",
      "O, him she stores, to show what wealth she had",
      "In days long since, before these last so bad.",
    ],
  },
  {
    title: "SONNET 68",
    lines: [
      "Thus is his cheek the map of days outworn,",
      "When beauty lived and died as flowers do now,",
      "Before the bastard signs of fair were born,",
      "Or durst inhabit on a living brow;",
      "Before the golden tresses of the dead,",
      "The right of sepulchres, were shorn away,",
      "To live a second life on second head",
      "Ere beauty's dead fleece made another gay:",
      "In him those holy antique hours are seen,",
      "Without all ornament, itself and true,",
      "Making no summer of another's green,",
      "Robbing no old to dress his beauty new;",
      "And him as for a map doth Nature store,",
      "To show false Art what beauty was of yore.",
    ],
  },
  {
    title: "SONNET 69",
    lines: [
      "Those parts of thee that the world's eye doth view",
      "Want nothing that the thought of hearts can mend;",
      "All tongues, the voice of souls, give thee that due,",
      "Uttering bare truth, even so as foes commend.",
      "Thy outward thus with outward praise is crown'd;",
      "But those same tongues that give thee so thine own",
      "In other accents do this praise confoun",
      "By seeing farther than the eye hath shown.",
      "They look into the beauty of thy mind,",
      "And that, in guess, they measure by thy deeds;",
      "Then, churls, their thoughts, although their eyes were kind,",
      "To thy fair flower add the rank smell of weeds:",
      "But why thy odour matcheth not thy show,",
      "The solve is this, that thou dost common grow.",
    ],
  },
  {
    title: "SONNET 74",
    lines: [
      "But be contented: when that fell arrest",
      "Without all bail shall carry me away,",
      "My life hath in this line some interest,",
      "Which for memorial still with thee shall stay.",
      "When thou reviewest this, thou dost review",
      "The very part was consecrate to thee:",
      "The earth can have but earth, which is his due;",
      "My spirit is thine, the better part of me:",
      "So then thou hast but lost the dregs of life,",
      "The prey of worms, my body being dead,",
      "The coward conquest of a wretch's knife,",
      "Too base of thee to be remembered.",
      "The worth of that is that which it contains,",
      "And that is this, and this with thee remains.",
    ],
  },
  {
    title: "SONNET 7",
    lines: [
      "So are you to my thoughts as food to life,",
      "Or as sweet-season'd showers are to the ground;",
      "And for the peace of you I hold such strife",
      "As 'twixt a miser and his wealth is found;",
      "Now proud as an enjoyer and anon",
      "Doubting the filching age will steal his treasure,",
      "Now counting best to be with you alone",
      "Then better'd that the world may see my pleasure;",
      "Sometime all full with feasting on your sight",
      "And by and by clean starved for a look;",
      "Possessing or pursuing no delight,",
      "Save what is had or must from you be took.",
      "Thus do I pine and surfeit day by day,",
      "Or gluttoning on all, or all away.",
    ],
  },
  {
    title: "SONNET 78",
    lines: [
      "So oft have I invoked thee for my Muse",
      "And found such fair assistance in my verse",
      "As every alien pen hath got my use",
      "And under thee their poesy disperse.",
      "Thine eyes that taught the dumb on high to sing",
      "And heavy ignorance aloft to fly",
      "Have added feathers to the learne's wing",
      "And given grace a double majesty.",
      "Yet be most proud of that which I compile,",
      "Whose influence is thine and born of thee:",
      "In others' works thou dost but mend the style,",
      "And arts with thy sweet graces graced be;",
      "But thou art all my art and dost advance",
      "As high as learning my rude ignorance.",
    ],
  },
  {
    title: "SONNET 79",
    lines: [
      "Whilst I alone did call upon thy aid,",
      "My verse alone had all thy gentle grace,",
      "But now my gracious numbers are decay'd",
      "And my sick Muse doth give another place.",
      "I grant, sweet love, thy lovely argument",
      "Deserves the travail of a worthier pen,",
      "Yet what of thee thy poet doth inven",
      "He robs thee of and pays it thee again.",
      "He lends thee virtue and he stole that word",
      "From thy behavior; beauty doth he give",
      "And found it in thy cheek; he can afford",
      "No praise to thee but what in thee doth live.",
      "Then thank him not for that which he doth say,",
      "Since what he owes thee thou thyself dost pay.",
    ],
  },
  {
    title: "SONNET 80",
    lines: [
      "O, how I faint when I of you do write,",
      "Knowing a better spirit doth use your name,",
      "And in the praise thereof spends all his might,",
      "To make me tongue-tied, speaking of your fame!",
      "But since your worth, wide as the ocean is,",
      "The humble as the proudest sail doth bear,",
      "My saucy bark inferior far to hi",
      "On your broad main doth wilfully appear.",
      "Your shallowest help will hold me up afloat,",
      "Whilst he upon your soundless deep doth ride;",
      "Or being wreck'd, I am a worthless boat,",
      "He of tall building and of goodly pride:",
      "Then if he thrive and I be cast away,",
      "The worst was this; my love was my decay.",
    ],
  },
  {
    title: "SONNET 81",
    lines: [
      "Or I shall live your epitaph to make,",
      "Or you survive when I in earth am rotten;",
      "From hence your memory death cannot take,",
      "Although in me each part will be forgotten.",
      "Your name from hence immortal life shall have,",
      "Though I, once gone, to all the world must die:",
      "The earth can yield me but a common grave",
      "When you entombed in men's eyes shall lie.",
      "Your monument shall be my gentle verse,",
      "Which eyes not yet created shall o'er-read,",
      "And tongues to be your being shall rehearse",
      "When all the breathers of this world are dead;",
      "You still shall live--such virtue hath my pen--",
      "Where breath most breathes, even in the mouths of men.",
    ],
  },
  {
    title: "SONNET 82",
    lines: [
      "I grant thou wert not married to my Muse",
      "And therefore mayst without attaint o'erlook",
      "The dedicated words which writers use",
      "Of their fair subject, blessing every book",
      "Thou art as fair in knowledge as in hue,",
      "Finding thy worth a limit past my praise,",
      "And therefore art enforced to seek ane",
      "Some fresher stamp of the time-bettering days",
      "And do so, love; yet when they have devised",
      "What strained touches rhetoric can lend,",
      "Thou truly fair wert truly sympathized",
      "In true plain words by thy true-telling friend;",
      "And their gross painting might be better used",
      "Where cheeks need blood; in thee it is abused.",
    ],
  },
  {
    title: "SONNET 83",
    lines: [
      "I never saw that you did painting need",
      "And therefore to your fair no painting set;",
      "I found, or thought I found, you did exceed",
      "The barren tender of a poet's debt;",
      "And therefore have I slept in your report,",
      "That you yourself being extant well might show",
      "How far a modern quill doth come too short",
      "Speaking of worth, what worth in you doth grow.",
      "This silence for my sin you did impute,",
      "Which shall be most my glory, being dumb;",
      "For I impair not beauty being mute,",
      "When others would give life and bring a tomb.",
      "There lives more life in one of your fair eyes",
      "Than both your poets can in praise devise.",
    ],
  },
  {
    title: "SONNET 84",
    lines: [
      "Who is it that says most? which can say more",
      "Than this rich praise, that you alone are you?",
      "In whose confine immured is the store",
      "Which should example where your equal grew.",
      "Lean penury within that pen doth dwell",
      "That to his subject lends not some small glory;",
      "But he that writes of you, if he can tel",
      "That you are you, so dignifies his story,",
      "Let him but copy what in you is writ,",
      "Not making worse what nature made so clear,",
      "And such a counterpart shall fame his wit,",
      "Making his style admired every where.",
      "You to your beauteous blessings add a curse,",
      "Being fond on praise, which makes your praises worse.",
    ],
  },
  {
    title: "SONNET 8",
    lines: [
      "My tongue-tied Muse in manners holds her still,",
      "While comments of your praise, richly compiled,",
      "Reserve their character with golden quill",
      "And precious phrase by all the Muses filed.",
      "I think good thoughts whilst other write good words,",
      "And like unletter'd clerk still cry 'Amen'",
      "To every hymn that able spirit afford",
      "In polish'd form of well-refined pen.",
      "Hearing you praised, I say 'Tis so, 'tis true,'",
      "And to the most of praise add something more;",
      "But that is in my thought, whose love to you,",
      "Though words come hindmost, holds his rank before.",
      "Then others for the breath of words respect,",
      "Me for my dumb thoughts, speaking in effect.",
    ],
  },
  {
    title: "SONNET 86",
    lines: [
      "Was it the proud full sail of his great verse,",
      "Bound for the prize of all too precious you,",
      "That did my ripe thoughts in my brain inhearse,",
      "Making their tomb the womb wherein they grew?",
      "Was it his spirit, by spirits taught to write",
      "Above a mortal pitch, that struck me dead?",
      "No, neither he, nor his compeers by nigh",
      "Giving him aid, my verse astonished.",
      "He, nor that affable familiar ghost",
      "Which nightly gulls him with intelligence",
      "As victors of my silence cannot boast;",
      "I was not sick of any fear from thence:",
      "But when your countenance fill'd up his line,",
      "Then lack'd I matter; that enfeebled mine.",
    ],
  },
  {
    title: "SONNET 89",
    lines: [
      "Say that thou didst forsake me for some fault,",
      "And I will comment upon that offence;",
      "Speak of my lameness, and I straight will halt,",
      "Against thy reasons making no defence.",
      "Thou canst not, love, disgrace me half so ill,",
      "To set a form upon desired change,",
      "As I'll myself disgrace: knowing th', will",
      "I will acquaintance strangle and look strange,",
      "Be absent from thy walks, and in my tongue",
      "Thy sweet beloved name no more shall dwell,",
      "Lest I, too much profane, should do it wrong",
      "And haply of our old acquaintance tell.",
      "For thee against myself I'll vow debate,",
      "For I must ne'er love him whom thou dost hate.",
    ],
  },
  {
    title: "SONNET 90",
    lines: [
      "Then hate me when thou wilt; if ever, now;",
      "Now, while the world is bent my deeds to cross,",
      "Join with the spite of fortune, make me bow,",
      "And do not drop in for an after-loss:",
      "Ah, do not, when my heart hath 'scoped this sorrow,",
      "Come in the rearward of a conquer'd woe;",
      "Give not a windy night a rainy morrow",
      "To linger out a purposed overthrow.",
      "If thou wilt leave me, do not leave me last,",
      "When other petty griefs have done their spite",
      "But in the onset come; so shall I taste",
      "At first the very worst of fortune's might,",
      "And other strains of woe, which now seem woe,",
      "Compared with loss of thee will not seem so.",
    ],
  },
  {
    title: "SONNET 92",
    lines: [
      "But do thy worst to steal thyself away,",
      "For term of life thou art assured mine,",
      "And life no longer than thy love will stay,",
      "For it depends upon that love of thine.",
      "Then need I not to fear the worst of wrongs,",
      "When in the least of them my life hath end.",
      "I see a better state to me belong",
      "Than that which on thy humour doth depend;",
      "Thou canst not vex me with inconstant mind,",
      "Since that my life on thy revolt doth lie.",
      "O, what a happy title do I find,",
      "Happy to have thy love, happy to die!",
      "But what's so blessed-fair that fears no blot?",
      "Thou mayst be false, and yet I know it not.",
    ],
  },
  {
    title: "SONNET 93",
    lines: [
      "So shall I live, supposing thou art true,",
      "Like a deceived husband; so love's face",
      "May still seem love to me, though alter'd new;",
      "Thy looks with me, thy heart in other place:",
      "For there can live no hatred in thine eye,",
      "Therefore in that I cannot know thy change.",
      "In many's looks the false heart's histor",
      "Is writ in moods and frowns and wrinkles strange,",
      "But heaven in thy creation did decree",
      "That in thy face sweet love should ever dwell;",
      "Whate'er thy thoughts or thy heart's workings be,",
      "Thy looks should nothing thence but sweetness tell.",
      "How like Eve's apple doth thy beauty grow,",
      "if thy sweet virtue answer not thy show!",
    ],
  },
  {
    title: "SONNET 94",
    lines: [
      "They that have power to hurt and will do none,",
      "That do not do the thing they most do show,",
      "Who, moving others, are themselves as stone,",
      "Unmoved, cold, and to temptation slow,",
      "They rightly do inherit heaven's graces",
      "And husband nature's riches from expense;",
      "They are the lords and owners of their faces",
      "Others but stewards of their excellence.",
      "The summer's flower is to the summer sweet,",
      "Though to itself it only live and die,",
      "But if that flower with base infection meet,",
      "The basest weed outbraves his dignity:",
      "For sweetest things turn sourest by their deeds;",
      "Lilies that fester smell far worse than weeds.",
    ],
  },
  {
    title: "SONNET 97",
    lines: [
      "How like a winter hath my absence been",
      "From thee, the pleasure of the fleeting year!",
      "What freezings have I felt, what dark days seen!",
      "What old December's bareness every where!",
      "And yet this time removed was summer's time,",
      "The teeming autumn, big with rich increase,",
      "Bearing the wanton burden of the prime",
      "Like widow'd wombs after their lords' decease:",
      "Yet this abundant issue seem'd to me",
      "But hope of orphans and unfather'd fruit;",
      "For summer and his pleasures wait on thee,",
      "And, thou away, the very birds are mute;",
      "Or, if they sing, 'tis with so dull a cheer",
      "That leaves look pale, dreading the winter's near.",
    ],
  },
  {
    title: "SONNET 98",
    lines: [
      "From you have I been absent in the spring,",
      "When proud-pied April dress'd in all his trim",
      "Hath put a spirit of youth in every thing,",
      "That heavy Saturn laugh'd and leap'd with him.",
      "Yet nor the lays of birds nor the sweet smell",
      "Of different flowers in odour and in hue",
      "Could make me any summer's story tell",
      "Or from their proud lap pluck them where they grew;",
      "Nor did I wonder at the lily's white,",
      "Nor praise the deep vermilion in the rose;",
      "They were but sweet, but figures of delight,",
      "Drawn after you, you pattern of all those.",
      "Yet seem'd it winter still, and, you away,",
      "As with your shadow I with these did play:",
    ],
  },
  {
    title: "SONNET 100",
    lines: [
      "Where art thou, Muse, that thou forget'st so long",
      "To speak of that which gives thee all thy might?",
      "Spend'st thou thy fury on some worthless song,",
      "Darkening thy power to lend base subjects light?",
      "Return, forgetful Muse, and straight redeem",
      "In gentle numbers time so idly spent;",
      "Sing to the ear that doth thy lays est",
      "And gives thy pen both skill and argument.",
      "Rise, resty Muse, my love's sweet face survey,",
      "If Time have any wrinkle graven there;",
      "If any, be a satire to decay,",
      "And make Time's spoils despised every where.",
      "Give my love fame faster than Time wastes life;",
      "So thou prevent'st his scythe and crooked knife.",
    ],
  },
  {
    title: "SONNET 101",
    lines: [
      "O truant Muse, what shall be thy amends",
      "For thy neglect of truth in beauty dyed?",
      "Both truth and beauty on my love depends;",
      "So dost thou too, and therein dignified.",
      "Make answer, Muse: wilt thou not haply say",
      "'Truth needs no colour, with his colour fix'd;",
      "Beauty no pencil, beauty's truth to lay",
      "But best is best, if never intermix'd?'",
      "Because he needs no praise, wilt thou be dumb?",
      "Excuse not silence so; for't lies in thee",
      "To make him much outlive a gilded tomb,",
      "And to be praised of ages yet to be.",
      "Then do thy office, Muse; I teach thee how",
      "To make him seem long hence as he shows now.",
    ],
  },
  {
    title: "SONNET 102",
    lines: [
      "My love is strengthen'd, though more weak in seeming;",
      "I love not less, though less the show appear:",
      "That love is merchandized whose rich esteeming",
      "The owner's tongue doth publish every where.",
      "Our love was new and then but in the spring",
      "When I was wont to greet it with my lays,",
      "As Philomel in summer's front doth sin",
      "And stops her pipe in growth of riper days:",
      "Not that the summer is less pleasant now",
      "Than when her mournful hymns did hush the night,",
      "But that wild music burthens every bough",
      "And sweets grown common lose their dear delight.",
      "Therefore like her I sometime hold my tongue,",
      "Because I would not dull you with my song.",
    ],
  },
  {
    title: "SONNET 106",
    lines: [
      "When in the chronicle of wasted time",
      "I see descriptions of the fairest wights,",
      "And beauty making beautiful old rhyme",
      "In praise of ladies dead and lovely knights,",
      "Then, in the blazon of sweet beauty's best,",
      "Of hand, of foot, of lip, of eye, of brow,",
      "I see their antique pen would have express'",
      "Even such a beauty as you master now.",
      "So all their praises are but prophecies",
      "Of this our time, all you prefiguring;",
      "And, for they look'd but with divining eyes,",
      "They had not skill enough your worth to sing:",
      "For we, which now behold these present days,",
      "Had eyes to wonder, but lack tongues to praise.",
    ],
  },
  {
    title: "SONNET 107",
    lines: [
      "Not mine own fears, nor the prophetic soul",
      "Of the wide world dreaming on things to come,",
      "Can yet the lease of my true love control,",
      "Supposed as forfeit to a confined doom.",
      "The mortal moon hath her eclipse endured",
      "And the sad augurs mock their own presage;",
      "Incertainties now crown themselves assure",
      "And peace proclaims olives of endless age.",
      "Now with the drops of this most balmy time",
      "My love looks fresh, and death to me subscribes,",
      "Since, spite of him, I'll live in this poor rhyme,",
      "While he insults o'er dull and speechless tribes:",
      "And thou in this shalt find thy monument,",
      "When tyrants' crests and tombs of brass are spent.",
    ],
  },
  {
    title: "SONNET 108",
    lines: [
      "What's in the brain that ink may character",
      "Which hath not figured to thee my true spirit?",
      "What's new to speak, what new to register,",
      "That may express my love or thy dear merit?",
      "Nothing, sweet boy; but yet, like prayers divine,",
      "I must, each day say o'er the very same,",
      "Counting no old thing old, thou mine, I thine",
      "Even as when first I hallow'd thy fair name.",
      "So that eternal love in love's fresh case",
      "Weighs not the dust and injury of age,",
      "Nor gives to necessary wrinkles place,",
      "But makes antiquity for aye his page,",
      "Finding the first conceit of love there bred",
      "Where time and outward form would show it dead.",
    ],
  },
  {
    title: "SONNET 109",
    lines: [
      "O, never say that I was false of heart,",
      "Though absence seem'd my flame to qualify.",
      "As easy might I from myself depart",
      "As from my soul, which in thy breast doth lie:",
      "That is my home of love: if I have ranged,",
      "Like him that travels I return again,",
      "Just to the time, not with the time exchanged",
      "So that myself bring water for my stain.",
      "Never believe, though in my nature reign'd",
      "All frailties that besiege all kinds of blood,",
      "That it could so preposterously be stain'd,",
      "To leave for nothing all thy sum of good;",
      "For nothing this wide universe I call,",
      "Save thou, my rose; in it thou art my all.",
    ],
  },
  {
    title: "SONNET 1",
    lines: [
      "Alas, 'tis true I have gone here and there",
      "And made myself a motley to the view,",
      "Gored mine own thoughts, sold cheap what is most dear,",
      "Made old offences of affections new;",
      "Most true it is that I have look'd on truth",
      "Askance and strangely: but, by all above,",
      "These blenches gave my heart another youth",
      "And worse essays proved thee my best of love.",
      "Now all is done, have what shall have no end:",
      "Mine appetite I never more will grind",
      "On newer proof, to try an older friend,",
      "A god in love, to whom I am confined.",
      "Then give me welcome, next my heaven the best,",
      "Even to thy pure and most most loving breast.",
    ],
  },
  {
    title: "SONNET 112",
    lines: [
      "Your love and pity doth the impression fill",
      "Which vulgar scandal stamp'd upon my brow;",
      "For what care I who calls me well or ill,",
      "So you o'er-green my bad, my good allow?",
      "You are my all the world, and I must strive",
      "To know my shames and praises from your tongue:",
      "None else to me, nor I to none alive",
      "That my steel'd sense or changes right or wrong.",
      "In so profound abysm I throw all care",
      "Of others' voices, that my adder's sense",
      "To critic and to flatterer stopped are.",
      "Mark how with my neglect I do dispense:",
      "You are so strongly in my purpose bred",
      "That all the world besides methinks are dead.",
    ],
  },
  {
    title: "SONNET 113",
    lines: [
      "Since I left you, mine eye is in my mind;",
      "And that which governs me to go about",
      "Doth part his function and is partly blind,",
      "Seems seeing, but effectually is out;",
      "For it no form delivers to the heart",
      "Of bird of flower, or shape, which it doth latch:",
      "Of his quick objects hath the mind no part",
      "Nor his own vision holds what it doth catch:",
      "For if it see the rudest or gentlest sight,",
      "The most sweet favour or deformed'st creature,",
      "The mountain or the sea, the day or night,",
      "The crow or dove, it shapes them to your feature:",
      "Incapable of more, replete with you,",
      "My most true mind thus makes mine eye untrue.",
    ],
  },
  {
    title: "SONNET 11",
    lines: [
      "Those lines that I before have writ do lie,",
      "Even those that said I could not love you dearer:",
      "Yet then my judgment knew no reason why",
      "My most full flame should afterwards burn clearer.",
      "But reckoning time, whose million'd accidents",
      "Creep in 'twixt vows and change decrees of kings,",
      "Tan sacred beauty, blunt the sharp'st intents",
      "Divert strong minds to the course of altering things;",
      "Alas, why, fearing of time's tyranny,",
      "Might I not then say 'Now I love you best,'",
      "When I was certain o'er incertainty,",
      "Crowning the present, doubting of the rest?",
      "Love is a babe; then might I not say so,",
      "To give full growth to that which still doth grow?",
    ],
  },
  {
    title: "SONNET 117",
    lines: [
      "Accuse me thus: that I have scanted all",
      "Wherein I should your great deserts repay,",
      "Forgot upon your dearest love to call,",
      "Whereto all bonds do tie me day by day;",
      "That I have frequent been with unknown minds",
      "And given to time your own dear-purchased right",
      "That I have hoisted sail to all the wind",
      "Which should transport me farthest from your sight.",
      "Book both my wilfulness and errors down",
      "And on just proof surmise accumulate;",
      "Bring me within the level of your frown,",
      "But shoot not at me in your waken'd hate;",
      "Since my appeal says I did strive to prove",
      "The constancy and virtue of your love.",
    ],
  },
  {
    title: "SONNET 122",
    lines: [
      "Thy gift, thy tables, are within my brain",
      "Full character'd with lasting memory,",
      "Which shall above that idle rank remain",
      "Beyond all date, even to eternity;",
      "Or at the least, so long as brain and heart",
      "Have faculty by nature to subsist;",
      "Till each to razed oblivion yield his part",
      "Of thee, thy record never can be miss'd.",
      "That poor retention could not so much hold,",
      "Nor need I tallies thy dear love to score;",
      "Therefore to give them from me was I bold,",
      "To trust those tables that receive thee more:",
      "To keep an adjunct to remember thee",
      "Were to import forgetfulness in me.",
    ],
  },
  {
    title: "SONNET 123",
    lines: [
      "No, Time, thou shalt not boast that I do change:",
      "Thy pyramids built up with newer might",
      "To me are nothing novel, nothing strange;",
      "They are but dressings of a former sight.",
      "Our dates are brief, and therefore we admire",
      "What thou dost foist upon us that is old,",
      "And rather make them born to our desir",
      "Than think that we before have heard them told.",
      "Thy registers and thee I both defy,",
      "Not wondering at the present nor the past,",
      "For thy records and what we see doth lie,",
      "Made more or less by thy continual haste.",
      "This I do vow and this shall ever be;",
      "I will be true, despite thy scythe and thee.",
    ],
  },
  {
    title: "SONNET 127",
    lines: [
      "In the old age black was not counted fair,",
      "Or if it were, it bore not beauty's name;",
      "But now is black beauty's successive heir,",
      "And beauty slander'd with a bastard shame:",
      "For since each hand hath put on nature's power,",
      "Fairing the foul with art's false borrow'd face,",
      "Sweet beauty hath no name, no holy bower",
      "But is profaned, if not lives in disgrace.",
      "Therefore my mistress' brows are raven black,",
      "Her eyes so suited, and they mourners seem",
      "At such who, not born fair, no beauty lack,",
      "Slandering creation with a false esteem:",
      "Yet so they mourn, becoming of their woe,",
      "That every tongue says beauty should look so.",
    ],
  },
  {
    title: "SONNET 129",
    lines: [
      "The expense of spirit in a waste of shame",
      "Is lust in action; and till action, lust",
      "Is perjured, murderous, bloody, full of blame,",
      "Savage, extreme, rude, cruel, not to trust,",
      "Enjoy'd no sooner but despised straight,",
      "Past reason hunted, and no sooner had",
      "Past reason hated, as a swallow'd bai",
      "On purpose laid to make the taker mad;",
      "Mad in pursuit and in possession so;",
      "Had, having, and in quest to have, extreme;",
      "A bliss in proof, and proved, a very woe;",
      "Before, a joy proposed; behind, a dream.",
      "All this the world well knows; yet none knows well",
      "To shun the heaven that leads men to this hell.",
    ],
  },
  {
    title: "SONNET 130",
    lines: [
      "My mistress' eyes are nothing like the sun;",
      "Coral is far more red than her lips' red;",
      "If snow be white, why then her breasts are dun;",
      "If hairs be wires, black wires grow on her head.",
      "I have seen roses damask'd, red and white,",
      "But no such roses see I in her cheeks;",
      "And in some perfumes is there more delight",
      "Than in the breath that from my mistress reeks.",
      "I love to hear her speak, yet well I know",
      "That music hath a far more pleasing sound;",
      "I grant I never saw a goddess go;",
      "My mistress, when she walks, treads on the ground:",
      "And yet, by heaven, I think my love as rare",
      "As any she belied with false compare.",
    ],
  },
  {
    title: "SONNET 131",
    lines: [
      "Thou art as tyrannous, so as thou art,",
      "As those whose beauties proudly make them cruel;",
      "For well thou know'st to my dear doting heart",
      "Thou art the fairest and most precious jewel.",
      "Yet, in good faith, some say that thee behold",
      "Thy face hath not the power to make love groan:",
      "To say they err I dare not be so bold",
      "Although I swear it to myself alone.",
      "And, to be sure that is not false I swear,",
      "A thousand groans, but thinking on thy face,",
      "One on another's neck, do witness bear",
      "Thy black is fairest in my judgment's place.",
      "In nothing art thou black save in thy deeds,",
      "And thence this slander, as I think, proceeds.",
    ],
  },
  {
    title: "SONNET 138",
    lines: [
      "When my love swears that she is made of truth",
      "I do believe her, though I know she lies,",
      "That she might think me some untutor'd youth,",
      "Unlearned in the world's false subtleties.",
      "Thus vainly thinking that she thinks me young,",
      "Although she knows my days are past the best,",
      "Simply I credit her false speaking tongue",
      "On both sides thus is simple truth suppress'd.",
      "But wherefore says she not she is unjust?",
      "And wherefore say not I that I am old?",
      "O, love's best habit is in seeming trust,",
      "And age in love loves not to have years told:",
      "Therefore I lie with her and she with me,",
      "And in our faults by lies we flatter'd be.",
    ],
  },
  {
    title: "SONNET 140",
    lines: [
      "Be wise as thou art cruel; do not press",
      "My tongue-tied patience with too much disdain;",
      "Lest sorrow lend me words and words express",
      "The manner of my pity-wanting pain.",
      "If I might teach thee wit, better it were,",
      "Though not to love, yet, love, to tell me so;",
      "As testy sick men, when their deaths be near",
      "No news but health from their physicians know;",
      "For if I should despair, I should grow mad,",
      "And in my madness might speak ill of thee:",
      "Now this ill-wresting world is grown so bad,",
      "Mad slanderers by mad ears believed be,",
      "That I may not be so, nor thou belied,",
      "Bear thine eyes straight, though thy proud heart go wide.",
    ],
  },
  {
    title: "SONNET 141",
    lines: [
      "In faith, I do not love thee with mine eyes,",
      "For they in thee a thousand errors note;",
      "But 'tis my heart that loves what they despise,",
      "Who in despite of view is pleased to dote;",
      "Nor are mine ears with thy tongue's tune delighted,",
      "Nor tender feeling, to base touches prone,",
      "Nor taste, nor smell, desire to be invite",
      "To any sensual feast with thee alone:",
      "But my five wits nor my five senses can",
      "Dissuade one foolish heart from serving thee,",
      "Who leaves unsway'd the likeness of a man,",
      "Thy proud hearts slave and vassal wretch to be:",
      "Only my plague thus far I count my gain,",
      "That she that makes me sin awards me pain.",
    ],
  },
  {
    title: "SONNET 143",
    lines: [
      "Lo! as a careful housewife runs to catch",
      "One of her feather'd creatures broke away,",
      "Sets down her babe and makes an swift dispatch",
      "In pursuit of the thing she would have stay,",
      "Whilst her neglected child holds her in chase,",
      "Cries to catch her whose busy care is bent",
      "To follow that which flies before her face",
      "Not prizing her poor infant's discontent;",
      "So runn'st thou after that which flies from thee,",
      "Whilst I thy babe chase thee afar behind;",
      "But if thou catch thy hope, turn back to me,",
      "And play the mother's part, kiss me, be kind:",
      "So will I pray that thou mayst have thy 'Will,'",
      "If thou turn back, and my loud crying still.",
    ],
  },
  {
    title: "SONNET 146",
    lines: [
      "Poor soul, the centre of my sinful earth,",
      "[] these rebel powers that thee array;",
      "Why dost thou pine within and suffer dearth,",
      "Painting thy outward walls so costly gay?",
      "Why so large cost, having so short a lease,",
      "Dost thou upon thy fading mansion spend?",
      "Shall worms, inheritors of this excess",
      "Eat up thy charge? is this thy body's end?",
      "Then soul, live thou upon thy servant's loss,",
      "And let that pine to aggravate thy store;",
      "Buy terms divine in selling hours of dross;",
      "Within be fed, without be rich no more:",
      "So shalt thou feed on Death, that feeds on men,",
      "And Death once dead, there's no more dying then.",
    ],
  },
  {
    title: "SONNET 147",
    lines: [
      "My love is as a fever, longing still",
      "For that which longer nurseth the disease,",
      "Feeding on that which doth preserve the ill,",
      "The uncertain sickly appetite to please.",
      "My reason, the physician to my love,",
      "Angry that his prescriptions are not kept,",
      "Hath left me, and I desperate now approv",
      "Desire is death, which physic did except.",
      "Past cure I am, now reason is past care,",
      "And frantic-mad with evermore unrest;",
      "My thoughts and my discourse as madmen's are,",
      "At random from the truth vainly express'd;",
      "For I have sworn thee fair and thought thee bright,",
      "Who art as black as hell, as dark as night.",
    ],
  },
  {
    title: "SONNET 150",
    lines: [
      "O, from what power hast thou this powerful might",
      "With insufficiency my heart to sway?",
      "To make me give the lie to my true sight,",
      "And swear that brightness doth not grace the day?",
      "Whence hast thou this becoming of things ill,",
      "That in the very refuse of thy deeds",
      "There is such strength and warrantize of skill",
      "That, in my mind, thy worst all best exceeds?",
      "Who taught thee how to make me love thee more",
      "The more I hear and see just cause of hate?",
      "O, though I love what others do abhor,",
      "With others thou shouldst not abhor my state:",
      "If thy unworthiness raised love in me,",
      "More worthy I to be beloved of thee.",
    ],
  },
  {
    title: "SONNET 151",
    lines: [
      "Love is too young to know what conscience is;",
      "Yet who knows not conscience is born of love?",
      "Then, gentle cheater, urge not my amiss,",
      "Lest guilty of my faults thy sweet self prove:",
      "For, thou betraying me, I do betray",
      "My nobler part to my gross body's treason;",
      "My soul doth tell my body that he ma",
      "Triumph in love; flesh stays no father reason;",
      "But, rising at thy name, doth point out thee",
      "As his triumphant prize. Proud of this pride,",
      "He is contented thy poor drudge to be,",
      "To stand in thy affairs, fall by thy side.",
      "No want of conscience hold it that I call",
      "Her 'love' for whose dear love I rise and fall.",
    ],
  },
  {
    title: "SONNET 153",
    lines: [
      "Cupid laid by his brand, and fell asleep:",
      "A maid of Dian's this advantage found,",
      "And his love-kindling fire did quickly steep",
      "In a cold valley-fountain of that ground;",
      "Which borrow'd from this holy fire of Love",
      "A dateless lively heat, still to endure,",
      "And grew a seething bath, which yet men prove",
      "Against strange maladies a sovereign cure.",
      "But at my mistress' eye Love's brand new-fired,",
      "The boy for trial needs would touch my breast;",
      "I, sick withal, the help of bath desired,",
      "And thither hied, a sad distemper'd guest,",
      "But found no cure: the bath for my help lies",
      "Where Cupid got new fire--my mistress' eyes.",
    ],
  },
];
